In [1]:
# Import Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy.stats as st
import seaborn as sn

In [2]:
sep2020 = pd.read_csv("202009-citibike-tripdata.csv")
oct2020 = pd.read_csv("202010-citibike-tripdata.csv")
nov2020 = pd.read_csv("202011-citibike-tripdata.csv")
dec2020 = pd.read_csv("202012-citibike-tripdata.csv")
jan2021 = pd.read_csv("202101-citibike-tripdata.csv")
feb2021 = pd.read_csv("202102-citibike-tripdata.csv")
mar2021 = pd.read_csv("202103-citibike-tripdata.csv")
apr2021 = pd.read_csv("202104-citibike-tripdata.csv")

In [3]:
sep2020.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,Customer,1979,1
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,Customer,1991,1

In [4]:
apr2021.head(2)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,370,2021-04-01 00:00:02.8730,2021-04-01 00:06:13.3450,4111,E 27 St & Park Ave S,40.742752,-73.984716,3798,W 40 St & 5 Ave,40.752269,-73.982079,36389,Customer,1970,0
1,2102,2021-04-01 00:00:04.7670,2021-04-01 00:35:07.2640,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,3859,Lorimer St & Calyer St,40.727950,-73.954140,52731,Customer,1970,0

In [6]:
citibike_df = pd.concat([sep2020, oct2020, nov2020, dec2020, jan2021, feb2021, mar2021, apr2021])
citibike_df.head(5)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,Customer,1979,1
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,Customer,1991,1
2,1097,2020-09-01 00:00:06.8990,2020-09-01 00:18:24.2260,3492,E 118 St & Park Ave,40.800539,-73.941995,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,41438,Subscriber,1984,1
3,1473,2020-09-01 00:00:07.7440,2020-09-01 00:24:41.1800,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,35860,Customer,1990,2
4,1193,2020-09-01 00:00:12.2020,2020-09-01 00:20:05.5470,3081,Graham Ave & Grand St,40.711863,-73.944024,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,26396,Customer,1969,0

In [7]:
citibike_df['gender']=citibike_df['gender'].replace([0, 1, 2],['Unknown', 'Male', 'Female'])

In [8]:
citibike_df.head(15)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,4225,2020-09-01 00:00:01.0430,2020-09-01 01:10:26.6350,3508,St Nicholas Ave & Manhattan Ave,40.809725,-73.953149,116,W 17 St & 8 Ave,40.741776,-74.001497,44317,Customer,1979,Male
1,1868,2020-09-01 00:00:04.8320,2020-09-01 00:31:13.7650,3621,27 Ave & 9 St,40.773983,-73.930913,3094,Graham Ave & Withers St,40.716981,-73.944859,37793,Customer,1991,Male
2,1097,2020-09-01 00:00:06.8990,2020-09-01 00:18:24.2260,3492,E 118 St & Park Ave,40.800539,-73.941995,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,41438,Subscriber,1984,Male
3,1473,2020-09-01 00:00:07.7440,2020-09-01 00:24:41.1800,3946,St Nicholas Ave & W 137 St,40.818477,-73.947568,4002,W 144 St & Adam Clayton Powell Blvd,40.820877,-73.939249,35860,Customer,1990,Female
4,1193,2020-09-01 00:00:12.2020,2020-09-01 00:20:05.5470,3081,Graham Ave & Grand St,40.711863,-73.944024,3048,Putnam Ave & Nostrand Ave,40.684020,-73.949770,26396,Customer,1969,Unknown
5,912,2020-09-01 00:00:12.8660,2020-09-01 00:15:25.4990,3738,Delancey St & Eldridge St,40.719383,-73.991479,3402,Court St & State St,40.690238,-73.992031,37276,Subscriber,1982,Male
6,393,2020-09-01 00:00:15.8420,2020-09-01 00:06:49.1560,501,FDR Drive & E 35 St,40.744219,-73.971212,501,FDR Drive & E 35 St,40.744219,-73.971212,25384,Subscriber,1977,Male
7,2477,2020-09-01 00:00:28.0470,2020-09-01 00:41:45.9820,3737,Stanton St & Norfolk St,40.720747,-73.986274,343,Clinton Ave & Flushing Ave,40.697940,-73.969868,46158,Subscriber,1988,Male
8,315,2020-09-01 00:00:29.5810,2020-09-01 00:05:44.8070,4024,Macombs Pl & W 152 St,40.826406,-73.937948,3967,W 146 St & Broadway,40.826969,-73.949738,36631,Customer,1969,Unknown
9,1554,2020-09-01 00:00:34.5600,2020-09-01 00:26:29.3760,3100,Nassau Ave & Newell St,40.724813,-73.947526,3530,Crescent St & Ditmars Blvd,40.778718,-73.914564,35902,Subscriber,1981,Male
10,1350,2020-09-01 00:00:40.0820,2020-09-01 00:23:10.8050,443,Bedford Ave & S 9 St,40.708531,-73.964090,396,Lefferts Pl & Franklin Ave,40.680342,-73.955769,33658,Customer,1969,Unknown
11,3281,2020-09-01 00:00:40.4390,2020-09-01 00:55:21.7210,302,Avenue D & E 3 St,40.720828,-73.977932,312,Allen St & Stanton St,40.722055,-73.989111,37041,Customer,1998,Female
12,606,2020-09-01 00:00:42.5460,2020-09-01 00:10:48.6900,3896,Madison St & Seneca Ave,40.701830,-73.906250,3845,Irving Ave & Harman St,40.701080,-73.917900,41865,Customer,1969,Unknown
13,1158,2020-09-01 00:00:49.8970,2020-09-01 00:20:08.6140,3179,Park Ave & Marcus Garvey Blvd,40.698617,-73.941342,3913,Sands St Gate,40.699569,-73.979827,44275,Subscriber,1969,Male
14,2043,2020-09-01 00:00:52.0520,2020-09-01 00:34:55.8350,3242,Schermerhorn St & Court St,40.691029,-73.991834,3409,Bergen St & Smith St,40.686744,-73.990632,29896,Subscriber,1990,Male

In [9]:
citibike_df.to_csv("citibikedata.csv", index=False, header=True)